.editorconfig

We like markdown files and this is a rule that makes our `.editorconfig` file respect markdown syntax of using 2 spaces for new lines.

Add editorconfig rule for markdown files

---

src/ui-lib/sass/02-generic/_layout.scss
src/ui-lib/sass/03-elements/_main.scss

On pages with not much content (e.g. the error page), the footer can appear in the middle of your viewport. This change ensures it is aligned to the bottom of the viewport - unless there is enough content for the page to be taller than the viewport. In that case, the page scrolls as usual.

Implemented sticky footer using flexbox.

---

src/ui-lib/sass/05-components/01-atoms/06-buttons/_08-toggle-menu.scss

Closes ticket WEB-157 
-changed units from rem to px - as rem's decimal precision seemed to be rounding incorrectly in some browsers, causing the gap offset.
-added new local variable for icon width to keep all sizes in px.
-fixed lint error

Web-157 (uneven gap between lines in burger menu)

---

package-lock.json
src/ui-lib/sass/05-components/01-atoms/10-navigation/_00-block-link.scss

added a white-space: nowrap to .grav-c-block-link to avoid this type of issue

WEB-154 About us / nav links no-wrap fix

---

src/ui-lib/sass/05-components/03-organisms/_job-list.scss

The goal was to make the baseline of the H2 text (the location of the jobs) and the first row of job card text to the right be aligned.
After some trial and error, I found that switching to flexbox to do the layout was the only way the `align-items: baseline;` had the desired effect consistently in Chrome, Firefox and Safari.
Maintaining the CSS grid-based layout didn't work everywhere. Only having flex on the outer `job-list` component but continuing to use CSS columns on the job cards didn't work in Firefox. etc.

Aligned baselines of location and jobs in job-list.

---

CHANGELOG.md
src/ui-lib/sass/05-components/03-organisms/00-page-structure/_01-page-footer.scss

The "Buildit@wipro digital" link in the footer was appearing in the blue (visited) colour in Firefox. This fixes that.

Fix footer link color

---

CHANGELOG.md
src/ui-lib/sass/05-components/03-organisms/00-page-structure/_00-page-header.scss

I noticed that on very narrow screens, the vertical alignment between the Buildit logo and the hamburger button wasn't ideal. They were top-aligned rather than centre aligned:
To fix that, I switched from floats to flexbox. That required updating some of the other code - however, I think the end result is a bit tidier overall.
Visually, the header appears identically to before on larger screens (tested in Firefox, Safari and Chrome on Mac).

Improved header layout on small viewports

---

.travis.yml
README.md
package.json

This PR updates the minimum required node and npm version.
By switching to `npm ci` we can skip the node_modules caching.
The first built took more time than actually required, I've run a second build to show that the build time is quite good, and we get all the benefits that `npm ci` provides: [https://docs.npmjs.com/cli/ci](https://docs.npmjs.com/cli/ci)

Updates travis to npm ci

---

CHANGELOG.md
src/ui-lib/sass/05-components/03-organisms/_hero.scss
src/ui-lib/sass/05-components/03-organisms/_two-columns-block.scss

A couple of CSS fixes were done in the website's code:
* Fix to hero because canvas (with dots animation) was sitting on top of text
* Tweak to locations page layout that makes cards align with outer edges of content area and left aligns last, dangling card
This PR backports those CSS changes into Gravity. Once they work their way into a future Gravity release, they can be deleted from the website's code.

Backporting website fixes

---

CHANGELOG.md
package-lock.json
package.json

We're getting spurious warnings due to a known bug in Pattern Lab (other than noise on the console, there's no adverse affects thought). I thought updating to the latest 2.x release might fix the issue. Unfortunately, it did not.
However, while I was at it, I figured I may as well update all our dependencies! It's good to keep up with bug fixes, enhancements etc. :-P
That's what this PR does.
Building, serving, linting etc. all work fine, so these updates appear to be safe :-)

Updated npm dependencies

---

CHANGELOG.md
src/ui-lib/js/gravity.js
src/ui-lib/sass/05-components/03-organisms/00-page-structure/_00-page-header.scss

In IE11 clicking the burger menu on small screens had no effect. Therefore, the navigation links were inaccessible.
It turns out that IE11 doesn't support arrow functions and also it doesn't have the `forEach()` method on the `NodeList` returned by `document.querySelectorAll();`. Therefore the JS execution died and the menu didn't work.
Additionally, the header was appearing excessively tall on IE11. It turned out to be the logo SVG. We have `height: auto;` which defaults to `150px` for inline SVGs but _should_ be overridden by the SVG's `height` attribute if one is set. It turns out that IE11 was ignoring the SVG's `height` attribute and therefore using the `150px` default instead. Setting a `max-height: 33px;` in the CSS fixed this (without adversely affecting other browsers).
This PR …

Fix IE burger menu

---

src/ui-lib/sass/05-components/03-organisms/_list-inline-row.scss

Closes ticket WEB-209 (Change partner logo link background colour on active state)
Set background to transparent to anchor elements inside list-inline-row.
Set anchor to inline-block to enable its children to fit inside of it, fixing the original issue of the background only covering half of its child elements.

Bug Fix (WEB-209): dark background block that only covers half of the logo's background 

---

CHANGELOG.md
src/styleguide/_patterns/03-organisms/00-page-structure/00-page-header.mustache
src/styleguide/_patterns/03-organisms/00-page-structure/01-page-footer.mustache
src/ui-lib/sass/02-generic/_heydon.scss
src/ui-lib/sass/05-components/03-organisms/00-page-structure/_00-page-header.scss
src/ui-lib/sass/05-components/03-organisms/00-page-structure/_01-page-footer.scss

According to the HTML validator, using `role="banner"` on a `<header>`, which is a direct descendant of `<body>` is redundant as those semantics are already implicit. Likewise, `role="contentinfo"` on `<footer>` is redundant as well.
This PR therefore removes those attributes from the patterns and updates the CSS accordingly. Consumers of Gravity don't _have to_ update their markup (the new CSS simply targets the elements rather than the attribute), so this is not a breaking change. However, they are strongly encouraged to do so, in order to avoid HTML validation warnings.

Page header & footer markup

---

CHANGELOG.md
src/ui-lib/sass/03-elements/_inline-text.scss
src/ui-lib/sass/05-components/03-organisms/00-page-structure/_00-page-header.scss

Changed inline text link colour on active state. 
Move active below visited for specificity - so that active overrides the visited colour.

Bug Fix (WEB-204): Changed inline text link colour on active state

---

src/ui-lib/sass/01-tools/_container.scss

This is [a IE11 bug](https://digitalrig.atlassian.net/browse/WEB-214) that happens when using margin: auto to fill all the available space between flex items. Here's more info [about this bug](https://github.com/philipwalton/flexbugs#flexbug-15)

Bug Fix (WEB-214) Target IE10+ for tools > container

---

CHANGELOG.md
package-lock.json
package.json

`npm audit` was recommending a few dependency updates to remove known vulnerabilities. This PR does that.
Note that some vulnerabilities remain, like the `hoek` ones (see #115), but until `node-sass` makes its next major release we can't do anything about those.

Updated some dependencies as recommended by npm audit.

---

CHANGELOG.md
src/styleguide/_patterns/02-molecules/00-navigation/00-nav-menu.mustache
src/styleguide/_patterns/03-organisms/00-page-structure/00-page-header.mustache
src/ui-lib/sass/05-components/02-molecules/00-navigation/_00-nav-menu.scss
src/ui-lib/sass/05-components/03-organisms/00-page-structure/_00-page-header.scss

Closes #131
This PR splits out the `toggle-menu` button from the `nav-menu` component, so that when the menu is viewed by itself in the pattern library, it is always visible.
Some of the associated CSS has been shuffled around a bit and simplified as well.

Separated toggle-menu button from nav-menu

---

.huskyrc.json
package.json

During `npm install`, `husky` was displaying a warning message that using `package.json`'s `scripts.pre-commit` was deprecated and you should migrate to either adding a `husky` section inside `package.json` or else using a Husky config file.
This PR implements the latter.
Note, no need to update the changelog as the unreleased changes still include the addition of Husky in the first place.

Migrate to .huskyrc file

---

CHANGELOG.md
CONTRIBUTING.md

Closes #18 
Adds the missing `CONTRIBUTING.md` file (largely copy-pasted from the Buildit website's one)

Contributing doc

---

.travis.yml

This fixes `master` releases to always trigger them whenever something is merged into the branch.
PS This is a hotfix so it should be released with GitFlow's hotfix tool. Meaning it's branched off of `master` and merged into `master` and `develop`

fix(releases): releases now always trigger on master instead of by tag

---

src/ui-lib/sass/03-elements/_lists.scss

Closes #173
The base styles for &lt;ul> and &lt;ol> had 2 issues: Nested lists were not indented and on some viewport sizes bullets would overflow to the left. This commit fixes those issues.
**Checklist**
Visually checked other patterns that use lists to ensure that they haven't been broken by these changes. Everything looks fine.
Setup a nested list to check that indentation now works. Here's a screenshot:

Fixes layout for lists

---

package.json

Closes #197 
Pegs our Eyeglass dependency to `2.2.1` because subsequent versions have a bug that breaks the build. (I have raised an issue with them, and once it's fixed, we should un-peg and upgrade this to the latest version.

fix: pin eyeglass to 2.2.1

---

.github/PULL_REQUEST_TEMPLATE.md
CHANGELOG.md
CONTRIBUTING.md
README.md
build-api.js
docs/branching-strategy.md
docs/build-api.md
docs/travis-ci.md
package-lock.json
package.json
src/styleguide/_patterns/00-particles/05-logos-and-icons/00-svg-symbols.md
src/styleguide/_patterns/01-atoms/00-inline-text/15-input.json
src/styleguide/_patterns/01-atoms/04-media/01-inline-svg-symbol.md
src/styleguide/_patterns/01-atoms/06-buttons/01-toggle-button.md

BREAKING CHANGE: NPM package has been renamed from `@buildit/gravity-ui-sass` to
`@buildit/gravity-ui-web`.
fix #201
Note to reviewers: Until we rename the git repo, some of the links in the docs will be broken.

Rename to gravity-ui-web

---

package-lock.json
package.json

Eyeglass 2.4.0 fixes the issue that caused us to pin it to 2.2.1 (see PR #199). This PR therefore upgrades up to 2.4.0

Greenkeeper/eyeglass 2.4.0

---

README.md

We had a warning in the README about the API still being in flux. Now that we've released v1.0.0
this is no longer true, so this message is being removed.

docs(readme): removes pre-production warning

---

.travis.yml

Commitlint was originally turned off to prevent old commits from causing Travis CI to fail.
Closes #210

ci(travis): enabled commitlint in Travis CI

---

src/ui-lib/sass/05-components/03-organisms/00-page-structure/_00-page-header.scss

A few whitespace issues that the SASS linter doesn't like snuck in. This fixes those.

fix(page-header): fixes linter issues

---

.gitignore
.travis.yml
cdn-index.template
scripts/cdn_publish.sh

Closes #191
Add publishing of master branch *.css, *.js, and an index.html to an S3 backed CloudFront CDN that
stores versions (i.e. https://static.buildit.digital/gravity/v1.0.1/gravity.css)
Will demo before merge

feat(deployment): add cdn publishing

---

.travis.yml

There was a bug in the `.travis.yml` that prevented the new `cdn_publish.sh` script from being called. This fixes that.

HOTFIX: fix(.travis.yml): cdn publish script now gets called correctly

---

.gitignore
scripts/cdn_publish.sh

ISSUES CLOSED: #235
Only publish to CDN if gravity-ui-web source changes are committed

chore(cdn_publish.sh): only publish to CDN for gravit-ui-web changes

---

packages/gravity-ui-web/package-lock.json
packages/gravity-ui-web/package.json

Version 3.0.0-alpha.1 published to npm as `next`

chore(release): bumped alpha version for \`next\` npm tag publish

---

packages/gravity-ui-web/filesizehistory.html
scripts/cdn_publish.sh
scripts/get_latest_version.sh
scripts/track_file_sizes.sh

refactor scripts to share common code and exclude files from history report
Refactor two scripts to use common code that gets version from Git.  Modify file size history report to filter out map files and json files from report.

chore(build): cleanup file size history report

---

packages/gravity-ui-web/src/sass/05-components/03-organisms/03-articles/_00-related-items.scss

The breakpoint code was updated whist the related items feature was in PR, so it got overlooked for refactoring.

fix(related items): used breakpoint code from typography changes

---

packages/gravity-ui-web/package-lock.json
packages/gravity-ui-web/src/sass/05-components/03-organisms/_hero.scss

I noticed a visual bug in the hero component, which was my fault. @ashblue originally had some relative positioning + z-index code to make the hero's white container overlap the banner image. I asked him to remove them - as I now realise, _incorrectly_ - thinking that the fact that the container is after the banner in the HTML source order, would suffice for it to visually overlap.
As it turns out, I wasn't quite right. While the `z-index`es are redundant, you do need to set `position: relative;` on the container to get the desired effect. So, this PR fixes that.
I'll be honest - I'm not 100% sure _why_ that's the case. Working off some experimentation @dw-buildit started, we've established that if the `<img>` was a `<div>` it would just …

fix(hero): makes container overlap banner

---

packages/gravity-ui-web/package-lock.json
packages/gravity-ui-web/package.json

chore(v3.0.0-alpha.2): updated version for npm release

---

packages/gravity-ui-nunjucks/src/_patterns/02-molecules/02-lists/05-three-column-list-justified.njk
packages/gravity-ui-web/src/sass/05-components/02-molecules/02-lists/05-three-column-list-justified.scss

affects: @buildit/gravity-ui-nunjucks, @buildit/gravity-ui-web
- Removed the need for an outer `<div>`
- Simplified in to one media query
- Used list defaults where appropriate
- Added padding in the three column layout, incase the contents of each column are wide
- Used gravity provided spacing variable for padding

refactor(3 col justified list): refactored for CR suggestions

---

package-lock.json
packages/gravity-ui-web/package-lock.json
packages/gravity-ui-web/package.json

Release to `next` tag containing 3 column justified list, updated color schemes, nav menu/header, and article work.

chore(release): graviy-ui-web v3.0.0-alpha.3 \`next\` release

---

packages/gravity-ui-web/src/sass/05-components/03-organisms/00-page-structure/_02-page-intro.scss

It looks like the font sizes changes slightly since when I set them to be smaller. Adjusted now.

refactor(page intro): font size is incorrect

---

packages/gravity-ui-web/src/sass/debug.scss

Closes #200
Invisible first child elements in the mark-up can cause unwanted side-effects for the layout (the website header is being affected by this for instance). This PR adds a new debug CSS rule will visually flag such issues in the browser, so that developers can fix their mark-up or CSS as needed.
Here's a screenshot of it in action:

New debug rule

---

packages/gravity-ui-web/package.json

Bump for latest `next` tagged release.
I've created documentation on how to complete this process here https://github.com/buildit/gravity-ui-web/wiki/Publishing-Next-Builds

chore(npm): published pacakge bump for next

---

packages/gravity-ui-web/src/sass/05-components/03-organisms/_callout.scss

Tweaks the layout of the callout component to better fit the website designs (some issues were spotted in the website PR: buildit/buildit#258
Specifically:
* Uses our container mixin (which, in effect does the same as `.grav-o-container`) to ensure that the inner DIV expands to the full width of the page content area
* Switches margin to padding on the outer DIV to create the desired spacing _within_ this component
* Switches some sizes from `em` to `rem` so that they stay consistent, even when text sizes change or get scaled
* Adds a max-width to the paragraph to match the concept designs more closely

fix(callout): tweaks layout

---

packages/gravity-ui-web/src/sass/01-tools/_layouts.scss
packages/gravity-ui-web/src/sass/05-components/03-organisms/_list-cards-basic.scss

The `.grav-c-list-cards-basic` component has an element modifier class that can stretch a single
card to span both columns. The CSS logic behind it might be useful to other column layouts, so this
change extracts and genericises it into a mixin that can be used in conjunction with any "no
danglies" column layout. It also updates the `.grav-c-list-cards.basic` class to use this mixin.

feat(column layout): adds mixin for full-width items

---

packages/gravity-ui-web/src/ui-lib/sass/01-tools/_container.scss

Fixes a long-standing bug that's been irking me:
The `grav-l-container` mixin, that is used by the `.grav-o-container` class and also within the page
header and footer components, sets a `max-width` but does not set an explicit `width`. Normally this is not an issue since block elements will naturally expand horizontally to fill the available space.
However, when used on direct descendents of `<body>`, which are laid out by flexbox for the sticky
footer behaviour), the elements shrink to fit the width of their content which causes them to then
appear centered on the page. This fix adds a `width: 100%;` to the mixin, which counteracts this
behaviour.
**Note**: I'm fixing this on `develop` since this bug has been present forever and I think it makes sense to do a `2.x` path …

fix: adds missing width property to grav-l-container() mixin

---

packages/gravity-ui-web/src/ui-lib/sass/01-tools/_container.scss

A recent fix to the container mixin incorrectly set the width as 100%, which failed to take into
account the outer margins that are applied on smaller viewports. This cause container components to
horizontally overflow the viewport. This fixes that by replacing 100% with a suitable calc()
expression.

fix: undoes layout regression caused by previous "fix"

---

packages/gravity-ui-web/src/sass/01-tools/_container.scss

Updated fix for @james-nash's stupid mistake (his words) for the `next` branch.

fix(container): undoes layout regression caused by previous "fix"

---

packages/gravity-ui-web/CHANGELOG.md

Merges automated version bump and changelist changes on `master` back into `develop`.

Merge v2.2.2 release into develop

---

packages/gravity-ui-web/src/sass/05-components/03-organisms/00-page-structure/_02-page-intro.scss
packages/gravity-ui-web/src/sass/05-components/03-organisms/_card-basic.scss

Adds a subtle background color to the card `img` element so that whilst loading there is a representation to the user of the notch etc.

refactor(basic card): use neutral alt bg color for slow loading images

---

packages/gravity-ui-web/src/sass/05-components/03-organisms/_callout.scss

Remove the margin above the three column list when the callout is in two column mode.

fix(callout): remove margin from list when in columns

---

.travis.yml

Turns out, contrary to their docs, Travis CI's environment still default to Python 2.x. Since we need 3.x, I've had to reinstate the `pyenv` call I recently removed. However, after some trial and error, I have determined that version `3.7` is available and works (previously we were trying to install `3.6` which was no longer an available version and therefore broke the builds).

chore(travis.yml): reinstates pyenv, but with correct version

---

.travis.yml

Travis builds from `develop` are now failing for the same reason that they recently were on `next`: `pyenv` is trying to switch to a Python version that is no longer available in the current Travis Linux images. The deployment therefore fails.
Example: https://travis-ci.org/buildit/gravity-ui-web/builds/578459635#L768
This PR applies the same change we used to fix this issue in `next` (see PR #340), i.e. it bumps the python version being installed.

chore(travis.yml): updates python version to fix deployments

---

package-lock.json
package.json

Closes #326
Auto-gneerated changes by Greenkeeper bot to bump some dev dependencies.
The bot was previously messing up and not updating `package-lock.json` alongside `package.json`, which then causes our builds to fail when they run `npm ci` - hence why it created issue #326. However, it seems to have resolved itself now.
Hopefully Greenkeeper will behave itself from now on.

Bump commitlint packages

---

packages/gravity-ui-web/src/sass/debug.scss

Updates debug.css to bring it inline with recent changes to Gravity's CSS classes. This also adds
some errors for v2 classes that have been removed in v3.
I've also thrown in a mixin to display warning messages for deprecated classes. It's not being used yet, but could be useful in future if we ever intend to deprecate things a few releases before the actually get removed.

refactor: updates debug.css

---

.nvmrc
package.json
packages/gravity-ui-web/package.json

* Expands the range of "compatible" Node and NPM versions to include releases newer than 8.x. This means that _consumers_ that `npm install` Gravity won't see warning messages if they're on Node versions later than 8 (currently they will)
* Updates `.nvmrc` to use the latest Node 10.x ("LTS Dubnium") versions as 8.x is no longer supported and pretty old now.
**Note to reviewers:** This PR is on the `develop` branch (i.e. Gravity 2.x)

fix(package): explicitly states compatibility with newer NodeJS versions

---

packages/gravity-ui-nunjucks/src/components/02-molecules/04-cards/00-card-basic/card-basic.njk
packages/gravity-ui-web/README.md

Closes #375 
Fix accessibility violations regarding to the `card-base` component. This component is using an `inlineSVG` element to show the SVG symbol `decorative-arrow-right` which by default doesn't have a title to be referenced. This was causing an ARIA error since there was mismatch between the `aria-labelledby` and the no existent title of that particular SVG symbol.
NOTE: Other solution could have been to add a `<title>` to the SVG symbol `decorative-arrow-right` but this title can change depending on the context where it is being used.
Also this PR fixes a typo in the README file.

fix(a11y): fix card violations

---

packages/gravity-ui-web/CHANGELOG.md

Merges the auto-generated release notes back into the `develop` branch.

Merge last release back into develop

---

packages/gravity-ui-nunjucks/src/components/03-organisms/00-page-structure/02-hero/hero.config.json
packages/gravity-ui-nunjucks/src/components/03-organisms/00-page-structure/02-hero/hero.njk

Closes #377 
In order to comply with accessibility requirements this PR adds an alternative description to the image of the `hero` component. This fix also solve `homepage` and `page-homepage` violations`.

fix(a11y): add alternative description to hero image

---

packages/gravity-ui-web/src/sass/03-elements/_media.scss
packages/gravity-ui-web/src/sass/05-components/03-organisms/_card-basic.scss
packages/gravity-ui-web/src/sass/05-components/03-organisms/_copy-ostentatious.scss

There can be some subtle layout glitches when `<img>` elements are wrapped in `<picture>` elements - especially when they also contain `<source>` elements before the image. This has been encountered on the Buildit website. These changes aim to avoid such problems and let  consumers use `<picture>`
without layout side-effects.

feat: improves picture element layout

---

packages/gravity-ui-web/package-lock.json
packages/gravity-ui-web/package.json

Simply bumps the `package.json` version to `3.0.0-alpha.10` to reflect the most recent NPM pre-release: https://www.npmjs.com/package/@buildit/gravity-ui-web/v/3.0.0-alpha.10

chore: publishes 3.0.0-alpha.10

---

packages/gravity-ui-web/src/sass/05-components/03-organisms/_card-basic.scss

When cards wrap their image in a <picture> element, it doesn't fill the width of the card as it
should. This fixes that.

fix(card-basic): fixes size of picture elements

---

packages/gravity-ui-nunjucks/src/components/00-particles/05-logos-and-icons/README.md
packages/gravity-ui-nunjucks/src/components/00-particles/05-logos-and-icons/logos-and-icons.njk
packages/gravity-ui-nunjucks/src/components/01-atoms/04-media/20-logotype/README.md
packages/gravity-ui-nunjucks/src/components/01-atoms/04-media/20-logotype/logotype.njk
packages/gravity-ui-nunjucks/src/sass/components/_svg-highlights.scss
packages/gravity-ui-nunjucks/src/sass/pattern-scaffolding.scss
packages/gravity-ui-web/src/sass/03-elements/_media.scss
packages/gravity-ui-web/src/sass/05-components/01-atoms/04-media/_10-logotype.scss
packages/gravity-ui-web/src/sass/05-components/01-atoms/_atoms.all.scss
packages/gravity-ui-web/src/sass/debug.scss

It turns out there was a flaw in our approach to letting parts of SVG symbols be recoloured. We had been selecting the classes that are used within the SVGs themselves (`grav-svg-hl-1 / 2 / 3`, which come from `gravity-particles`) and then applying certain colour purposes to them. However, this only works globally for all instances of those SVG symbols and does not allow the colouring to be altered or disabled on a case by case basis.
The reason is as follows: We inline all our SVG symbols on the page, but since they are `<symbol>` elements, they don't visually render. Wherever we then display one of those symbols, we create an `<svg>` element that contains a `<use>` element referencing the desired SVG symbol. This essentially clones that symbol's contents into the our …

feat(logotype): changes SVG colouring and adds new logotype component

---

.travis.yml

Semantic release seemed to hang on the recent v3 release. However, it did seem to work - at least partially - since the NPM package was published, a git tag and changelog was pushed back to this repo and Github release notes were added.
However, because it didn't seem to exit the TravisCI build timed out and failed. Because of this, subsequent steps to publish the updated pattern library and CDN copy did not execute :-(
Sadly, the build log doesn't offer any clues. I've tried running the same command locally and it seems to complete fine. Maybe it was a one-off glitch?
Semantic release is executed via Lerna, which buffers the output until the command completes. That's why we never got to see whatever semantic release might have been outputting to the console. This commit …

chore(ci): streams semantic-release output
