.stylelintrc
package-lock.json
package.json

Added Stylelint as dev dependency and added a basic configuration file for it.
There are some more in depth rules we can use, but at the moment this might suffice? Suggestions are welcome, maybe we can come up with a more strict set of rules before this gets merged.

added stylelint

---

.travis.yml
README.md

Travis CI setup to deploy living styleguide website

---

package-lock.json
package.json
src/ui-lib/sass/00-settings/_gravy.scss
src/ui-lib/sass/00-settings/_modularscale.scss
src/ui-lib/sass/00-settings/_typography.scss
src/ui-lib/sass/gravity.scss

- added normalize and modularscale
- configured modularscale
- upgraded stylelint and related deps
- added base typi config

Improved Typography - base settings

---

src/styleguide/_data/data.json
src/styleguide/_patterns/02-molecules/01-careers/01-job-card.md
src/styleguide/_patterns/02-molecules/01-careers/01-job-card.mustache
src/styleguide/_patterns/03-organisms/01-lists/00-job-list.md
src/styleguide/_patterns/03-organisms/01-lists/00-job-list.mustache
src/styleguide/_patterns/04-templates/01-careers.mustache
src/styleguide/_patterns/05-pages/01-careers.json
src/styleguide/_patterns/05-pages/01-careers.mustache
src/ui-lib/sass/03-elements/_semantic.scss
src/ui-lib/sass/05-components/02-molecules/_job-card.scss
src/ui-lib/sass/05-components/03-organisms/_job-list.scss
src/ui-lib/sass/gravity.scss

- added careers template
- added careers page
- added link to careers page from basic page
- added data structures and variables
- added page specific variables

Careers page

---

src/ui-lib/sass/00-settings/_gravy.scss
src/ui-lib/sass/00-settings/_typography.scss
src/ui-lib/sass/03-elements/_buttons.scss
src/ui-lib/sass/03-elements/_headings.scss
src/ui-lib/sass/03-elements/_inline-text.scss
src/ui-lib/sass/03-elements/_tables.scss

- set styles to the right weight
- added pointers to buttons

improved typography

---

src/styleguide/_patterns/02-molecules/00-navigation/00-nav-menu.mustache
src/styleguide/_patterns/03-organisms/00-page-structure/00-page-header.mustache
src/styleguide/_patterns/05-pages/00-page-layouts/00-basic-page.json
src/ui-lib/sass/00-settings/_gravy.scss
src/ui-lib/sass/02-generic/_layout.scss
src/ui-lib/sass/03-elements/_main-content.scss
src/ui-lib/sass/05-components/02-molecules/00-navigation/_00-nav-menu.scss
src/ui-lib/sass/05-components/03-organisms/00-page-structure/_00-page-header.scss

- added new breakpoint
- renamed breakpoint medium to regular

updated look and feel for header and menu

---

src/styleguide/_patterns/01-atoms/06-buttons/07-cta.json
src/styleguide/_patterns/01-atoms/06-buttons/07-cta.md
src/styleguide/_patterns/01-atoms/06-buttons/07-cta.mustache
src/styleguide/_patterns/01-atoms/06-buttons/07-cta~disabled.json
src/ui-lib/sass/00-settings/_animations.scss
src/ui-lib/sass/00-settings/_colors.scss
src/ui-lib/sass/00-settings/_strokes.scss
src/ui-lib/sass/05-components/01-atoms/06-buttons/_07-cta.scss
src/ui-lib/sass/05-components/03-organisms/_steps.scss
src/ui-lib/sass/gravity.scss

- added normal and disabled states
- added animation variables
- added generic accessors for accent colours
- added larger thickness size
- updated style of steps

added CTA button

---

src/styleguide/_patterns/04-templates/00-about.mustache
src/styleguide/_patterns/04-templates/00-page-layouts/00-basic-page.mustache
src/styleguide/_patterns/04-templates/01-careers.mustache
src/styleguide/_patterns/04-templates/02-locations.mustache
src/ui-lib/sass/01-tools/_container.scss
src/ui-lib/sass/05-components/03-organisms/00-page-structure/_00-page-header.scss
src/ui-lib/sass/05-components/03-organisms/00-page-structure/_01-page-footer.scss
src/ui-lib/sass/05-components/03-organisms/_container.scss
src/ui-lib/sass/06-utilities/_container.scss
src/ui-lib/sass/gravity.scss

- created `grav-l-container` mixin
- created `grav-l-container` class
- removed style from `main` element
- refactored markup to use new utility class
- added mixin to header and footer
- cleaned up header
- cleaned up footer

added utility class for layout container

---

src/ui-lib/sass/05-components/03-organisms/_job-list.scss

- It fixes the first li inside a grav-c-job-list > ul

Fixes job list alignment

---

src/styleguide/_data/data.json
src/styleguide/_patterns/03-organisms/00-page-structure/03-section.md
src/styleguide/_patterns/03-organisms/00-page-structure/03-section.mustache
src/styleguide/_patterns/04-templates/00-homepage.mustache
src/styleguide/_patterns/04-templates/01-about.mustache
src/styleguide/_patterns/05-pages/00-homepage.json
src/styleguide/_patterns/05-pages/01-about.json
src/ui-lib/sass/02-generic/_heydon.scss
src/ui-lib/sass/03-elements/_lists.scss
src/ui-lib/sass/gravity.scss

- created new organism `section`
- added documentation for the new pattern
- adjusted style for text
- added style for lists

Added more copy to homepage

---

src/styleguide/_patterns/01-atoms/06-buttons/08-toggle-menu.md
src/styleguide/_patterns/01-atoms/06-buttons/08-toggle-menu.mustache
src/styleguide/_patterns/02-molecules/00-navigation/00-nav-menu.mustache
src/ui-lib/sass/01-tools/_clear.scss
src/ui-lib/sass/01-tools/_container.scss
src/ui-lib/sass/03-elements/_tables.scss
src/ui-lib/sass/05-components/01-atoms/06-buttons/_08-toggle-menu.scss
src/ui-lib/sass/05-components/01-atoms/10-navigation/_00-block-link.scss
src/ui-lib/sass/05-components/02-molecules/00-navigation/_00-nav-menu.scss
src/ui-lib/sass/05-components/02-molecules/01-cards/_location-card.scss
src/ui-lib/sass/05-components/03-organisms/00-page-structure/_00-page-header.scss
src/ui-lib/sass/05-components/03-organisms/_hero.scss
src/ui-lib/sass/05-components/03-organisms/_job-list.scss
src/ui-lib/sass/gravity.scss

- extracted toggle button for better style
- added clear mixin
- removed margin from container
- refactored page hearder
- refactored nav-menu
- fixed inline menu at largers sizes
- best effort fix for menu on small devices
- various stylelint fixes

Refactored nav menu

---

.vscode/settings.json

Just to ensure that everyone is going to see the same SASS errors and warnings.
[stylelint marketplace link](https://marketplace.visualstudio.com/items?itemName=shinnn.stylelint)

VSCode stylelint workspace settings

---

src/styleguide/_patterns/03-organisms/01-careers/00-job-list.mustache
src/styleguide/_patterns/05-pages/02-careers.json

- cleaned up careers page json
- organised cities by country code

WEB-131 - mirrored jobs from current website

---

package-lock.json
package.json

The build is set up to default to master, therefore this fix is needed in order to build correctly

Develop to Master PR for fixing build

---

src/styleguide/_patterns/04-templates/00-page-layouts/01-error-page.mustache
src/styleguide/_patterns/05-pages/00-page-layouts/00-basic-page.json
src/styleguide/_patterns/05-pages/00-page-layouts/01-error-page.json
src/ui-lib/sass/04-objects/_section.scss

- Added section object which adds margin top (used to fix error page layout)
- Updated JSON data for the primary nav

Fixing layout and json data

---

src/styleguide/_patterns/03-organisms/00-page-structure/02-hero.mustache
src/styleguide/_patterns/05-pages/00-homepage.mustache
src/ui-lib/sass/05-components/03-organisms/_hero.scss

This is the initial work for the hero banner for the js work that will be added to the buildit website
- _hero.scss : changed to gradient, added canvas css
- 02-hero.mustache : removed bg url, closed p tag

WEB-141 - Animated hero dots image

---

src/ui-lib/sass/05-components/03-organisms/00-page-structure/_00-page-header.scss

Bug Fix (WEB-208): Added hover state on title in the header

---

CHANGELOG.md
src/styleguide/_patterns/01-atoms/04-media/25-icon.json
src/styleguide/_patterns/05-pages/00-homepage.json
src/styleguide/_patterns/05-pages/00-page-layouts/00-basic-page.json
src/styleguide/_patterns/05-pages/00-page-layouts/01-error-page.json
src/styleguide/_patterns/05-pages/01-about.json
src/styleguide/_patterns/05-pages/02-careers.json
src/styleguide/_patterns/05-pages/03-locations.json

Closes #59 and fixes some embarrassing oversights from when I renamed the SVG icon IDs.

Fixed broken icon references and added Github to page footers.

---

src/styleguide/_patterns/05-pages/00-homepage.json

Fixed broken Abbott link.

---

CHANGELOG.md

Some of our older CHANGELOG entries weren't rendering correctly due to non-space characters being present (can happen in VS Code is you accidentally type SHIFT + SPACE). This fixes that.
Most (all?) of the checklist below does not apply. Will only tick things that are relevant.

Fixed fake spaces in CHANGELOG that were screwing up the rendering

---

CHANGELOG.md
src/ui-lib/sass/05-components/01-atoms/06-buttons/_08-toggle-menu.scss

Make sure these boxes are checked before submitting and approving PRs - Thank you!
If there are any exceptions, please make sure to explain why this is the case:

Fatter burger menu

---

CHANGELOG.md
src/styleguide/_patterns/01-atoms/06-buttons/07-cta.md
src/styleguide/_patterns/01-atoms/06-buttons/07-cta.mustache
src/styleguide/_patterns/01-atoms/06-buttons/08-toggle-menu.md
src/styleguide/_patterns/01-atoms/06-buttons/08-toggle-menu.mustache
src/styleguide/_patterns/02-molecules/00-navigation/00-nav-menu.mustache
src/styleguide/_patterns/03-organisms/00-page-structure/00-page-header.json
src/styleguide/_patterns/03-organisms/00-page-structure/00-page-header.mustache
src/styleguide/_patterns/03-organisms/00-page-structure/00-page-header~home.json
src/styleguide/_patterns/03-organisms/00-page-structure/00-page-header~light.json
src/styleguide/_patterns/04-templates/00-homepage.json
src/styleguide/_patterns/05-pages/00-homepage.json
src/styleguide/css/components/_dark-background.scss
src/styleguide/css/pattern-scaffolding.scss
src/ui-lib/sass/05-components/01-atoms/06-buttons/_07-cta.scss
src/ui-lib/sass/05-components/01-atoms/06-buttons/_08-toggle-menu.scss
src/ui-lib/sass/05-components/01-atoms/10-navigation/_00-block-link.scss
src/ui-lib/sass/05-components/03-organisms/00-page-structure/_00-page-header.scss

Fixes #113 
Make sure these boxes are checked before submitting and approving PRs - Thank you!
If there are any exceptions, please make sure to explain why this is the case:

Issue-113: Made header transparent

---

CHANGELOG.md

Just updating the changelog. Once approved, I'll do `npm version` and kick off the Travis release build.

Prepping v0.10.0 release

---

CHANGELOG.md
package-lock.json
src/styleguide/_patterns/01-atoms/06-buttons/07-cta.mustache
src/styleguide/_patterns/03-organisms/00-page-structure/00-page-header.mustache
src/ui-lib/sass/00-settings/_gravy.scss
src/ui-lib/sass/05-components/01-atoms/06-buttons/_07-cta.scss
src/ui-lib/sass/05-components/01-atoms/06-buttons/_08-toggle-menu.scss
src/ui-lib/sass/05-components/02-molecules/00-navigation/_00-nav-menu.scss
src/ui-lib/sass/05-components/03-organisms/00-page-structure/_00-page-header.scss

Make sure these boxes are checked before submitting and approving PRs - Thank you!
If there are any exceptions, please make sure to explain why this is the case:

Improved UX of mobile nav

---

CHANGELOG.md
src/styleguide/_patterns/04-templates/00-page-layouts/01-error-page.mustache
src/styleguide/_patterns/04-templates/01-about.mustache

This PR fixes some instances of nested `.grav-o-container` elements, which on small viewports lead to oversized horizontal margins between the viewport and page content.
This bugs were flagged up by the recently merged Debug CSS PR #146.

Fix superfluous containers

---

.travis.yml
CHANGELOG.md
package-lock.json
package.json

Closes #164
* Updated various dependencies
* Updated Travis config to use .nvmrc for Node version and no longer update NPM version.

Housekeeping

---

README.md

This is branched off from https://github.com/buildit/gravity-ui-sass/pull/192 and contains additional docs for importing Gravity SASS relating to the changed merged here https://github.com/buildit/gravity-ui-sass/pull/194

Itcss import docs

---

package.json

Added contributors Daniel Wilkinson and Charles 'Ash Blue' Brindle

Adds recent contributors

---

scripts/cdn_publish.sh

Fixes the expression used to capture git version tag

ci(cdn_publish.sh): fix the version tag expression

---

scripts/cdn_publish.sh

ISSUES CLOSED: #237
Adds latest directory in CDN to point to to always get the latest version of artifacts as well as latest major version (1.x, 2.x, etc) directories

chore(cdn_publish.sh): add latest and latest major dirs

---

packages/gravity-ui-nunjucks/src/_patterns/02-molecules/04-cards/00-card-basic.md
packages/gravity-ui-nunjucks/src/_patterns/02-molecules/04-cards/00-card-basic.njk
packages/gravity-ui-web/src/sass/00-settings/_animations.scss
packages/gravity-ui-web/src/sass/00-settings/_settings.all.scss
packages/gravity-ui-web/src/sass/00-settings/_transition-speeds.scss
packages/gravity-ui-web/src/sass/01-tools/_tools.all.scss
packages/gravity-ui-web/src/sass/01-tools/_transitions.scss
packages/gravity-ui-web/src/sass/05-components/01-atoms/06-buttons/_07-cta.scss
packages/gravity-ui-web/src/sass/05-components/01-atoms/06-buttons/_08-toggle-menu.scss
packages/gravity-ui-web/src/sass/05-components/03-organisms/00-page-structure/_00-page-header.scss
packages/gravity-ui-web/src/sass/05-components/03-organisms/_card-basic.scss
packages/gravity-ui-web/src/sass/05-components/03-organisms/_list-cards-basic.scss
packages/gravity-ui-web/src/sass/05-components/03-organisms/_list-image-links.scss
packages/gravity-ui-web/src/svg-symbols/decoration-arrow-right.svg

affects: @buildit/gravity-ui-nunjucks, @buildit/gravity-ui-web
Adds rollover (hover) effects to the basic card component when it is being used with a link.

feat(basic card): added hover colour and svg icon treatment

---

package-lock.json
package.json

Merging in a safe dependency version bump identied by the Greenkeeper bot

Greenkeeper/husky 2.3.0

---

.travis.yml

upgrade python on travis to newest version to get rid of SNI SSL issues with aws install and calls

Upgrade travis python

---

.travis.yml

chore(.travis.yml): change python version to minor only

---

packages/gravity-ui-web/package-lock.json
packages/gravity-ui-web/package.json

Publishes some of the recent updates, so that we can get them into other projects.

Preps 3.0.0 alpha 4 pre-release

---

packages/gravity-ui-web/publish-prerelease.sh

Helper script for pre releasing

chore(npm): new prerelease publish shell script

---

cdn-index.template

Updates the link to the change log in the cdn-index.template to the new location

chore(cdn-index.template): update link to change log

---

packages/gravity-ui-web/CHANGELOG.md

Merges the updated `package.json` and `CHANGELOG` made by `semantic-release` into `develop`.

Get release into develop

---

packages/gravity-ui-nunjucks/package.json
packages/gravity-ui-web/package-lock.json
packages/gravity-ui-web/package.json

Version bumps from release ` v3.0.0-alpha.6` NPM package.

Release v3.0.0-alpha.6

---

package-lock.json
package.json
packages/gravity-ui-web/CHANGELOG.md
packages/gravity-ui-web/src/sass/01-tools/_container.scss
packages/semantic-release/lerna-analyzer/package-lock.json
packages/semantic-release/release-notes-generator/package-lock.json

Merge develop into next

---

package-lock.json
package.json
packages/gravity-ui-web/CHANGELOG.md
packages/gravity-ui-web/package-lock.json
packages/gravity-ui-web/package.json
packages/gravity-ui-web/src/sass/05-components/01-atoms/02-lists/_01-list-horizontal.scss
packages/semantic-release/config/package-lock.json
packages/semantic-release/config/package.json
packages/semantic-release/lerna-analyzer/package-lock.json
packages/semantic-release/lerna-analyzer/package.json
packages/semantic-release/release-notes-generator/package-lock.json
packages/semantic-release/release-notes-generator/package.json

Merges latest Gravity 2.x updates from `develop` into `next`.

Dev into next

---

packages/gravity-ui-web/package-lock.json
packages/gravity-ui-web/package.json

chore: 🤖 3.0.0-alpha-7 pre-release

---

packages/gravity-ui-nunjucks/src/components/01-atoms/02-lists/04-n-column-list/README.md
packages/gravity-ui-nunjucks/src/components/01-atoms/02-lists/04-n-column-list/n-column-list.njk
packages/gravity-ui-web/src/sass/04-objects/_layouts.scss

Closes #358 
Add 3 column class layout and its documentation.

Add 3 column layout class

---

package-lock.json
package.json
packages/eslint/package-lock.json
packages/eslint/package.json
packages/gravity-ui-nunjucks/package-lock.json
packages/gravity-ui-nunjucks/package.json
packages/gravity-ui-web/package-lock.json
packages/gravity-ui-web/package.json
packages/semantic-release/config/package-lock.json
packages/semantic-release/config/package.json
packages/semantic-release/lerna-analyzer/package-lock.json
packages/semantic-release/lerna-analyzer/package.json
packages/semantic-release/release-notes-generator/package-lock.json
packages/semantic-release/release-notes-generator/package.json
packages/tests/ui-web-eyeglass/package-lock.json
packages/tests/ui-web-eyeglass/package.json
packages/tests/ui-web-node-sass-import/package-lock.json
packages/tests/ui-web-node-sass-import/package.json
packages/tests/ui-web-sass-loader/package-lock.json
packages/tests/ui-web-sass-loader/package.json
packages/tests/ui-web-sass/package-lock.json
packages/tests/ui-web-sass/package.json

Bumps a crapton of NPM dependencies to the latest available versions.

chore: bumps all dependencies
